title: Younes Sahraoui
description: Portfolio of an IT student
url: "https://ii0ns.github.io"
baseurl: ""
lang: en
timezone: Europe/Paris
collections:
  projects:
    output: true
    permalink: /projects/:name/
defaults:
  - scope: { path: "", type: projects }
    values: { layout: project }
exclude: [README.md]
